
export enum MediaType {
  ANIME = 'Anime',
  MANGA = 'Manga',
  MANHWA = 'Manhwa',
  BOOK = 'Book',
}

export enum UserStatus {
  READING = 'Reading/Watching',
  COMPLETED = 'Completed',
  PLAN_TO_READ = 'Plan to Read',
  ON_HOLD = 'On Hold',
  DROPPED = 'Dropped',
}

export interface UserProfile {
  name: string;
  age: number | string;
}

export interface MediaItem {
  id: string; // Unique ID (often generated by Gemini or local UUID)
  title: string;
  originalTitle?: string;
  type: MediaType;
  format: string; // TV, Movie, Novel, Webtoon, etc.
  synopsis: string;
  totalCount: number | null; // Total episodes or chapters. Null if ongoing/unknown.
  coverUrl?: string; // We will generate seed-based placeholder if API doesn't give one
  genres: string[];
  
  // User specific data
  userStatus: UserStatus;
  userProgress: number; // Current chapter/episode
  userScore: number; // 0-10
  addedAt: number; // Timestamp
  updatedAt: number; // Timestamp
  group?: string; // Custom group name for Kanban board
}

export interface SearchResultItem {
  id: string; // Placeholder ID
  title: string;
  type: MediaType;
  format: string;
  synopsis: string;
  totalCount: number | null;
  coverUrl?: string;
  genres: string[];
}

export interface Character {
  name: string;
  role: string;
  imageUrl?: string;
}

export interface MediaDetails extends SearchResultItem {
  trailerUrl?: string;
  characters?: Character[];
  relations?: { title: string; type: string; id: string }[];
}

export type ViewState = 'DASHBOARD' | 'LIBRARY' | 'SEARCH' | 'SETTINGS' | 'DETAILS';
